name: "DOS Stub IoC Injector"
description: "Adds an Indicator of Compromise into the DOS stub section of a PE binary for post-deployment detection or forensic analysis."
inputs:
  BINARY_PATH:
    description: 'Path to the PE file to modify (will be overwritten)'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Upgrade pip and install pefile
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pefile

    - name: Modify PE file
      shell: bash
      run: python "${{ github.action_path }}/modify_pe.py"
      env:
        INPUT_BINARY_PATH: ${{ inputs.BINARY_PATH }}