name: "User Notification"
description: "Display the provided description message as a notification and immediately continue the workflow—no approval required."
runs:
  using: "composite"
  steps:
    - name: User Notification
      shell: powershell
      run: |
        $repository_name = $env:GITHUB_REPOSITORY
        $repository_id = $env:GITHUB_REPOSITORY_ID
        $repository_owner = $env:GITHUB_REPOSITORY_OWNER
        $repository_owner_id = $env:GITHUB_REPOSITORY_OWNER_ID
        $workflow_name = $env:GITHUB_WORKFLOW
        $workflow_sha = $env:GITHUB_WORKFLOW_SHA
        $actor = $env:GITHUB_ACTOR
        $actor_id = $env:GITHUB_ACTOR_ID
        $time = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

        $message = "Repository: $repository_name ($repository_id)`n" +
                   "Owner: $repository_owner ($repository_owner_id)`n" +
                   "Workflow: $workflow_name (SHA: $workflow_sha)`n" +
                   "Triggered by: $actor ($actor_id)`n" +
                   "Executed at: $time"
        
        $result = (New-Object -ComObject WScript.Shell).Popup($message, 10, "GitHub Actions Notification", 48)