name: c2
on:
  workflow_dispatch:
    inputs:
      hostlabels:
        description: 'Host label to execute'
        type: string
        required: true
      command_type:
        description: 'Command type'
        type: choice
        required: true
        options:
          - 'shell'
          - 'javascript'
          - 'download'
          - 'upload'
          - 'custom-module'
#      shell_type:
#        type: choice
#        required: false
#        options:
#          - 'auto'
#          - 'bash'
#          - 'pwsh'
#          - 'python'
#          - 'sh'
#          - 'cmd'
#          - 'powershell'
#        default: 'auto'
      sourcecode:
        type: string
        description: 'Shell script(PowerShell/Bash) or JavaScript source code to execute (Required if command type is shell/javascript)'
        required: false
        default: ''
      filepath:
        type: string
        description: 'Filepath to download file (Required if command type is download, otherwise blank)'
        required: false
      run_name:
        type: string
        description: 'run-name dynamically determined by c2-manual-interface workflow/CLI Tool'
        required: false
      module_name:
        type: string
        description: 'Custom module workflow name'
        required: false
        default: ''

run-name: "${{ inputs.run_name || format('c2-{0}-{1}{2}{3}', inputs.command_type, inputs.sourcecode, inputs.filepath, inputs.module_name) }}"

jobs:
  c2run:
    name: c2
    #strategy:
    #  matrix:
    #    #hostlabels: ${{ fromJson(format('[{0}]', inputs.hostlabels)) }}
    #    hostlabels: ${{ fromJson(inputs.hostlabels) }}
    #runs-on: ${{ matrix.hostlabels }}
    runs-on: ${{ inputs.hostlabels }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Request User Approval
        uses: ./.github/actions/utils/require-user-approval

      # If you prefer notification only instead of approval:
      #- name: User Notification
      #  uses: ./.github/actions/utils/user-notification
        
      - name: shell
        if: ${{ inputs.command_type == 'shell' }}
        # steps.run.shell can't access inputs (or other) context?
        #shell: ${{ inputs.shell_type == 'auto' && (runner.os == 'Windows' && 'pwsh' || 'bash') || inputs.shell_type }}
        run: "${{ inputs.sourcecode }}"
        
      - name: download
        uses: actions/upload-artifact@v4
        if: ${{ inputs.command_type == 'download' }}
        with:
          name: "${{ inputs.filepath }}"
          path: "${{ inputs.filepath }}"
          
      - name: javascript
        uses: actions/github-script@v3
        if: ${{ inputs.command_type == 'javascript' }}
        with:
          script: "${{ inputs.sourcecode }}"
          
      - name: upload
        uses: actions/checkout@v4
        if: ${{ inputs.command_type == 'upload' }}
        with:
          ref: "upload"  # branch name
          path: "upload"
          
  custom-module:
    name: custom-mdule
    if: ${{ inputs.command_type == 'custom-module' }}
    #uses: ./.github/workflows/${{ inputs.module_name }}.yaml
    #with:
    #  hostlabels: ${{ inputs.hostlabels }}
    runs-on: ubuntu-latest
    env:
      C2_WORKFLOW_BRANCH_NAME: c2-workflow
    steps:
      - name: invoke-custom-module 
        if: ${{ inputs.command_type == 'custom-module' }}
        run: |
          REPO=$(echo "${{ github.repository }}" | sed -e "s#.*/##")
          OWNER="${{ github.repository_owner }}"

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/$OWNER/$REPO/actions/workflows/${{ inputs.module_name }}.yaml/dispatches \
            -d '{
              "ref": "${{ env.C2_WORKFLOW_BRANCH_NAME }}",
              "inputs": {
                  "hostlabels": "${{ inputs.hostlabels }}"
              }
            }'

